---
title: "Milieu Intérieur Project: Cytokine Data Analysis"
date: "2023-06-10"
author: "Violaine Saint-André"

## License
#  Milieu Intérieur Project: Cytokine Data Analysis
#     Copyright (C) 2023  Violaine Saint-André
#     contact: violaine.saint-andre@pasteur.fr
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
---

## Set parameters and import libraries
```{r, results="hide"}

# import libraries
library(dplyr)
library(tidyr)
library(gridExtra)
library(rmarkdown)
library(reshape2)
library(RColorBrewer) 
library(scales)
library(cowplot)
library(ggplot2)

# set path for results
pathRes <- "./RESULTS"

```

## Import proteomic matrix

```{r, results="hide"}
df.data <- read.table(file="./TableS1.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE)

# remove the donors that have been reprocessed
  # adding 302 as it is missing values for LPS 
  # removed 883 who removed consent for everything
df.data.v1 <- df.data %>% 
  filter(!(DonorId %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701, 302, 883))) 

dta <- df.data.v1[,c(1,2:ncol(df.data.v1))]

#Log transformation
dta.log <- dta
dta.log[,4:ncol(dta)] <- log(dta[,4:ncol(dta)])
dataProt <- dta.log

head(dataProt)

```

# Import covariates
```{r, results="hide"}

##prepare vectors
listKept <- list()
list5p <- list()
list1level <- list()
critRejete <- list()
curr_col_names_all_filtered <- list()
col_names_cat <- list()
col_names_num <- list()


df_data_all <- read.table(file = "./DM_2018-09-04_13-49-19.csv",
                          dec = ",",
                          sep=';', 
                          header = TRUE,
                          stringsAsFactors = FALSE) #,
df_data_all <- df_data_all  %>% mutate_all(as.character) %>% 
  filter(!(SUBJID %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701))) 
df_data_all$SUBJID <- as.character(df_data_all$SUBJID)
df_data_all <- df_data_all[order(df_data_all$SUBJID),]

df_data_rej <-read.table(file = "./DM_2018-09-04_13-49-19.csv",
                         dec = ",",
                         sep=';', 
                         header = TRUE,
                         stringsAsFactors = FALSE)#, 
df_data_rej <- df_data_rej  %>% mutate_all(as.character) %>% 
  filter(!(SUBJID %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701))) 
df_data_rej$SUBJID <- as.character(df_data_rej$SUBJID)
df_data_rej <- df_data_all[order(df_data_rej$SUBJID),]


  labkeyTable="HLA.database.csv"
  
  print(labkeyTable)
  
  df_data <- read.table(file = labkeyTable,
                        dec = ",",
                        sep=';', 
                        header = TRUE,
                        stringsAsFactors = FALSE)
              
  df_data <- as.data.frame(df_data) 
  
  
  df_data <- df_data  %>% mutate_all(as.character)  %>%
    filter(!(SUBJID %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701))) 
  
  df_data <- df_data[order(df_data$SUBJID),]
  
  print(head(df_data))
  
  df_datavar <- read.table(file = "./Variable_trans_mod_HLAdot.csv",
                           sep = ";",
                           dec = ",",
                           header = TRUE,
                           fill = TRUE,
                           stringsAsFactors = FALSE) 
                           
  
  df_datavar_cat <- df_datavar %>% filter(CATEGORY %in% c("cat", "freetext"))
  df_datavar_num <- df_datavar %>% filter(CATEGORY %in% c("num"))
  df_datavar_all <- df_datavar %>% filter(CATEGORY %in% c("cat", "num", "likert"))
  
  curr_col_names_cat <- intersect(df_datavar_cat$VARIABLE, names(df_data))
  curr_col_names_num <- intersect(df_datavar_num$VARIABLE, names(df_data))
  curr_col_names_all <- intersect(df_datavar_all$VARIABLE, names(df_data))
  
  df_data[,curr_col_names_num] <- apply(df_data[,curr_col_names_num, drop=F],2, function(x) as.numeric(gsub(",", ".", as.character(x))))
  df_data[,curr_col_names_cat] <- apply(df_data[,curr_col_names_cat, drop=F],2, function(x) as.character(x))
  
  
  col_names_cat <-c(col_names_cat, curr_col_names_cat)
  col_names_num <-c(col_names_num, curr_col_names_num)
  
  for (crit in curr_col_names_cat) {
    if (length(table(df_data[,crit])) > 1){
      test <- table(df_data[,crit]) > 49
      if (sum(test) > length(table(df_data[,crit]))/2){
        curr_col_names_all_filtered <- c(curr_col_names_all_filtered, crit)    
        df_data_all <- merge(df_data_all, df_data[, c(crit,'SUBJID'), drop=F], by = 'SUBJID') 
        listKept <- c(listKept, crit) 
      }
      else{
        print("less than 5% crit ")
        print(crit)
        list5p <- c(list5p, crit) 
        critRejete <-c(critRejete, crit) 
        df_data_rej <- merge(df_data_rej, df_data[, c(crit,'SUBJID'), drop=F], by = 'SUBJID')
      }
    }
    else{
      print("less than 1 level factor ")
      print(crit)
      list1level <- c(list1level, crit) 
      critRejete <-c(critRejete, crit) 
      df_data_rej <- merge(df_data_rej, df_data[, c(crit,'SUBJID'), drop=F], by = 'SUBJID') 
    }
  }
  
  for (crit in curr_col_names_num) {
  df_data_all <- merge(df_data_all, df_data[, c(crit,'SUBJID'), drop=F], by = 'SUBJID')
  }

dim(df_data_all)
dim(df_data_rej)

length(df_data_all) 

# > colnames(df_data_all)
#[1] "SUBJID"           "HLA.C.1.2D"       "HLA.C.2.2D"       "HLA.DPA1.1.2D"    "HLA.DPA1.2.2D"    "HLA.DQA1.1"       "HLA.DQA1.2"       "HLA.DQB1.1.2D"   
 #[9] "HLA.DQB1.2.2D"    "HLA.DQB1.GENO.2D" "HLA.DRB1.2.2D"    "HLA.A.1.P"        "HLA.A.2.P"        "HLA.B.1.P"        "HLA.B.2.P"        "HLA.C.1.P"       
#[17] "HLA.C.2.P"        "HLA.DPA1.1.P"     "HLA.DPA1.2"       "HLA.DPA1.2.P"     "HLA.DPB1.1.P"     "HLA.DPB1.2.P"     "HLA.DQA1.1.P"     "HLA.DQA1.2.P"    
#[25] "HLA.DQB1.1.P"     "HLA.DQB1.2.P"     "HLA.DRB1.1.P"     "HLA.DRB1.2.P"    


```




# make regressions 
```{r, results="hide"}
# prepare the lists
mat_effect_size_E <- list()
mat_effect_size_sd_low <- list()
mat_effect_size_sd_high <- list()
mat_p_val <- list()
significatif <- list()
heatmapList <- list()
list_matDATAPvalFDR <- list()

# loop on all stimulations 
  
for (stimul in c("SEB", "E.coli", "BCG", "C.albicans",  "CD3+CD28", "LPS", "PolyIC", "Null","Influenza","IL1b", 'IFNg',"TNFa" )){  
  
  print(paste0('stimul=',stimul))
  diffMat <- matrix(stimul, nrow = 998, ncol = 12)
  
  # to work on expressed prot only
  dta_Null <- dataProt[dataProt$StimulusName == "Null",]
  dta_stim <- dataProt[dataProt$StimulusName == stimul,]
  diffMat<- dta_stim[,4:16]-dta_Null[,4:16]
  
  medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
  id <- medianVal > log(1.3)
  protList <- colnames(dta_stim[4:16][,id])  
  
  curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
  curr_dta[,1:3] <- dta_stim[,1:3]
  n <- length(protList)+3
  curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
  curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
  dta_stimul <- curr_dta
  
  
    # exceptions
  
  if (stimul == "TNFa") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "TNFa")] 
    protList <- setdiff(protList, "TNFa")
  }
  
  if (stimul == "IL1b") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "IL1b")] 
    protList <- setdiff(protList, "IL1b")
  }
  
  if (stimul == "IFNg") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "FNg")] 
    protList <- setdiff(protList, "IFNg")
 }
                      
                    
   if (stimul ==  "CD3+CD28") {
    dta_CD3_CD28 <- dataProt[dataProt$StimulusName == "CD3+CD28",]
    
    # separate data in 2 groups
    dta_CD3_CD28num <- as.data.frame(apply(dta_CD3_CD28[, 4:16], 2, as.numeric), na.rm = T)
    # replace NAs by imputation
    cl <- kmeans(Hmisc::impute(dta_CD3_CD28num), 2)
    dta_CD3_CD28_grp1 <- dta_CD3_CD28[which(cl$cluster==1),]
    dta_CD3_CD28_grp2 <- dta_CD3_CD28[which(cl$cluster==2),]
    
    # then use the right group 
    if (dim(dta_CD3_CD28_grp1)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp1
      ind_CD3_CD28 <- dta_stim$DonorId
    }
    
    else if (dim(dta_CD3_CD28_grp2)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp2
      ind_CD3_CD28 <- dta_stim$DonorId
    }
  
    # use the right indices for the Null
    diffMat<- dta_stim[,4:16]-dta_Null[dta_stim$DonorId,4:16]
    medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
    id <- medianVal > log(1.3)
    protList <- colnames(dta_stim[4:16][,id])

    curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
    curr_dta[,1:3] <- dta_stim[,1:3]
    n <- length(protList)+3
    curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
    curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
    dta_stimul <- curr_dta

  }
  
  if (stimul ==  "Null") {
    dta_stimul <- dataProt[dataProt$StimulusName == "Null",]
    protList <- colnames(dta_stimul[4:16])
  }
  
  
  # merge the dataframes
  
  if (stimul == "CD3+CD28"){
    DF <- DF[match(ind_CD3_CD28, DF$DonorId),]
    DF <- merge.data.frame(dta_stimul, df_data_all, by.x = "DonorId", by.y = "SUBJID")
  } else {
    DF <- merge.data.frame(dta_stimul, df_data_all, by.x = "DonorId", by.y = "SUBJID")
  }
  
  # make regressions
  
  matList <- list()
  matDATA <- list()
  matDATAPval <- list()
  p_val <- list()
  listFit <- list()
  effect_size_E_list <- list()
  effect_size_sd_low_list <- list()
  effect_size_sd_high_list <- list()
  listFitPval <- list()
  p_val_list <- list()
 
  for (i in protList) {  
    print (i)
    listCrit <- list()
    effect_size_E <- list()
    effect_size_sd_low <- list()
    effect_size_sd_high <- list()
    listPval <- list()
  
   for (crit in colnames(df_data_all %>% dplyr::select (-'SUBJID'))){
   
      if (crit %in% col_names_cat) {
        
        DF2 <- na.omit(DF[,c(crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 with crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x + AGE.V0  +  SEX + BatchId), 
                                                         list( y = i, x = crit))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        fitmA <- anova(fitm)
        
        # model 2 without crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ AGE.V0 + SEX + BatchId ),
                                                          list(y= i))))[2], data=DF2)
        fitmA2 <- anova(fitm2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[crit] <- fit[2,'Pr(>Chi)']
        
        # recover p-val and ES
        
        listCrit[crit] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[crit]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                           .Names=levelsCrit)
        
        p_val[[crit]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                   .Names=levelsCrit)
        
        effect_size_sd_low[[crit]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        
        effect_size_sd_high[[crit]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
      }
      
      else if (crit %in% col_names_num) {
        
        DF2 <- na.omit(DF[,c(crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 with crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x + AGE.V0  + SEX + BatchId), 
                                                         list(  y = i, x = crit))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        
        # model 2 without crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~  AGE.V0 + SEX + BatchId),
                                                          list( y = i))))[2], data=DF2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[crit] <- fit[2,'Pr(>Chi)']
        
        # recover p-val and ES
        
        listCrit[crit] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[crit]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                           .Names=levelsCrit)
        
        p_val[[crit]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                   .Names=levelsCrit)
                                    
        effect_size_sd_low[[crit]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        
        effect_size_sd_high[[crit]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
      }
      
    }
    
    listFit[[i]] <- unlist(listCrit)
    
    listFitPval[[i]] <- unlist(listPval)
    
    effect_size_E_list[[i]] <- unlist(effect_size_E)
    effect_size_sd_low_list[[i]] <- unlist(effect_size_sd_low)
    effect_size_sd_high_list[[i]] <- unlist(effect_size_sd_high)
    p_val_list[[i]] <- unlist(p_val)
  }
  
  
  # recreate matrices
  
  mat_effect_size_E[[stimul]] <- as.data.frame(effect_size_E_list)
  mat_effect_size_sd_low[[stimul]] <- as.data.frame(effect_size_sd_low_list)
  mat_effect_size_sd_high[[stimul]] <- as.data.frame(effect_size_sd_high_list)
  mat_p_val[[stimul]] <- as.data.frame(p_val_list)
  
  # FDR for all
  
   matDATAPval <- as.data.frame(listFitPval)
   matDATAPvalFDR <-matrix(nrow=nrow(matDATAPval), ncol=ncol(matDATAPval), data=p.adjust(unlist(matDATAPval), method='BY'))
   colnames(matDATAPvalFDR) <- colnames(matDATAPval)
   rownames(matDATAPvalFDR) <- rownames(matDATAPval)
   
   list_matDATAPvalFDR[[stimul]] <- matDATAPvalFDR
  
   matDATAselect <- apply(matDATAPvalFDR,1, function (x) (x< 0.01))
   matDATAselect <- matDATAselect[,colSums(matDATAselect) >= 1]
   matDATAselect <- t(matDATAselect)
   
   colM <- colnames(matDATAselect)
   rowM <- rownames(matDATAselect)
   significatif[[stimul]]  <- rowM

   melted_matDATA <- melt(as.matrix(matDATAPvalFDR))
  #
  melted_matDATA$value <- -log10(melted_matDATA$value)
  melted_matDATA$stars <- cut(melted_matDATA$value, breaks=c(-Inf, 1.30103, 2, 3, Inf), label=c("", "*", "**", "***"))
  medianValue <- median(melted_matDATA$value, na.rm=T)
  
  
   heatmapList[[stimul]] <- ggplot(melted_matDATA, aes(x=Var2, y=Var1, fill=value)) +
     geom_tile()+
     scale_fill_gradient2(low="dark blue", mid="light blue", high="red", midpoint=medianValue) +
     #scale_fill_gradient2(low="dark blue", mid="light blue", high="red", limits=c(0,30)) +
    geom_text(aes(label=stars), color="black", size=3) +
    labs(y="", x="", fill="") +
    theme(legend.key.size = unit(1, "cm")) +
    theme_bw() +
    guides(fill = guide_colourbar(barwidth = 0.5,
                                barheight = 3))+
    theme(axis.text.x=element_text(angle = -90, hjust = 0), axis.text = element_text(size = 6))+
    theme(axis.text = element_text(size = 6)) +
    ggtitle(stimul)
  
  ggsave(plot=marrangeGrob(grobs=heatmapList, nrow=4, ncol=3),width = 8.27, height = 11.69, filename = paste0(pathRes, '/HLAvsCytokines_', Sys.Date(), '.pdf')) # for A4 format
  
   write.table(as.data.frame(melted_matDATA),file=paste0(pathRes, "/AdjPvalHLA_", stimul,"_",Sys.Date(),".txt"), quote=F, row.names = F, col.names = T, sep="\t")
  }


```  

