---
title: "Milieu Intérieur Project: Cytokine Data Analysis"
date: "2023-06-10"
author: "Violaine Saint-André"

## License
#  Milieu Intérieur Project: Cytokine Data Analysis
#     Copyright (C) 2023  Violaine Saint-André
#     contact: violaine.saint-andre@pasteur.fr
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
---

## Set parameters and import libraries
```{r, results="hide"}

# import libraries
library(dplyr)
library(tidyr)
library(gridExtra)
library(rmarkdown)
library(reshape2)
library(RColorBrewer) 
library(scales)
library(cowplot)
library(ggplot2)

# set path for results
pathRes <- "./RESULTS"

```

## Import proteomic matrix

```{r, results="hide"}
df.data <- read.table(file="./TableS1.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE)

# remove the donors that have been reprocessed
df.data.v1 <- df.data %>% 
  # adding 302 as it is missing values for LPS 
  # removed 883 who removed consent for everything
  filter(!(DonorId %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701, 302, 883))) 

dta <- df.data.v1[,c(1,2:ncol(df.data.v1))]

# log transformation
dta.log <- dta
dta.log[,4:ncol(dta)] <- log(dta[,4:ncol(dta)])
dataProt <- dta.log

head(dataProt)

```

## Upload the cellular data
```{r, results="hide"}

#  non imputed counts
df_counts <- read.table("./facs_counts_renamed.txt", header=TRUE, sep='\t', dec = ".", stringsAsFactors = FALSE)
df_counts[,2:ncol(df_counts)] <- log(df_counts[ ,2:ncol(df_counts)]+1)  

# arrange names
colnames(df_counts) <- sub('[.][^.]+$', '', colnames(df_counts))
colnames(df_counts) <- sub('N_', '', colnames(df_counts))
colnames(df_counts)

```

## Import covariates
```{r, results="hide"}
# on all selected variables
df_data_all <- read.table(file="./TableS2.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE) 
colnames(df_data_all)

length(df_data_all) #137
df_data_all133names <- colnames(df_data_all)

# set categorical and numerical variables
col_names_cat <- list()
col_names_num <- list()

#df_datavar <- read.table(file = "./Variable_trans_mod.csv",
#                           sep = ";",
#                           dec = ",",
#                           header = TRUE,
#                           fill = TRUE,
#                           stringsAsFactors = FALSE)
#df_datavarShort <- df_datavar[,c("VARIABLE","VAR.DESC", "VAR.VAL","Value", "CATEGORY")]

#df_datavarShort <- df_datavarShort[df_datavarShort$VARIABLE %in% names(df_data_all),]
#dim(df_datavarShort) 
#write.table(as.data.frame(df_datavarShort),paste("./df_datavarShort.txt"),  quote=F, row.names = F, sep="\t")

df_datavar <- read.table(file = "./df_datavarShort.txt",
                           sep = "\t",
                           dec = ",",
                           header = TRUE,
                           fill = TRUE,
                           stringsAsFactors = FALSE)

df_datavar_cat <- df_datavar %>% filter(CATEGORY %in% c("cat"))
df_datavar_num <- df_datavar %>% filter(CATEGORY %in% c("num"))
df_datavar_all <- df_datavar %>% filter(CATEGORY %in% c("cat", "num", "likert"))
  
curr_col_names_cat <- intersect(df_datavar_cat$VARIABLE, names(df_data_all))
curr_col_names_num <- intersect(df_datavar_num$VARIABLE, names(df_data_all))
curr_col_names_all <- intersect(df_datavar_all$VARIABLE, names(df_data_all))

# transform numerical data into numeric  
df_data_all[,curr_col_names_num] <- apply(df_data_all[,curr_col_names_num, drop=F],2, function(x) as.numeric(gsub(",", ".", as.character(x))))
df_data_all[,curr_col_names_cat] <- apply(df_data_all[,curr_col_names_cat, drop=F],2, function(x) as.character(x))
  
col_names_cat <-c(col_names_cat, curr_col_names_cat)
col_names_num <-c(col_names_num, curr_col_names_num)

# selection of variables
df_data_allsel <- df_data_all[,c('SUBJID', 'AGE.V0', 'SEX', 'TABAC.T1','NBYLTABAC', 'NBYTABAC', 'TOTNROFCIGS', 'WEIGHT.V0', 'ABDOCM.V0', 'BMI.V0', 'FC.V0','CMV.V1', 'BIERE','PLATC')]


```

## Run regressions
```{r, results="hide"}

# prepare the lists
mat_effect_size_E <- list()
mat_effect_size_sd_low <- list()
mat_effect_size_sd_high <- list()
mat_p_val <- list()
significatif <- list()
heatmapList <- list()
list_matDATAPvalFDR <- list()

# loop on all stimulations 
stimul= "SEB"
  
#for (stimul in c("SEB", "E.coli", "BCG", "C.albicans",  "CD3+CD28", "LPS", "PolyIC", "Null","Influenza","IL1b", 'IFNg',"TNFa" )){  
  print(paste0('stimul=',stimul))
  diffMat <- matrix(stimul, nrow = 998, ncol = 12)
  
  # to work on expressed prot only
  dta_Null <- dataProt[dataProt$StimulusName == "Null",]
  dta_stim <- dataProt[dataProt$StimulusName == stimul,]
  diffMat<- dta_stim[,4:16]-dta_Null[,4:16]
  
  medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
  id <- medianVal > log(1.3)
  protList <- colnames(dta_stim[4:16][,id])  
  
  curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
  curr_dta[,1:3] <- dta_stim[,1:3]
  n <- length(protList)+3
  curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
  curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
  dta_stimul <- curr_dta
  dta_stimul <- merge.data.frame(dta_stimul, df_counts, by.x = "DonorId", by.y = "SUBJID")
  
  
  # exceptions
  if (stimul == "TNFa") {dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "IL1b")] 
  protList <- setdiff(protList, "IL1b")}
                      
   if (stimul ==  "CD3+CD28") {
    dta_CD3_CD28 <- dataProt[dataProt$StimulusName == "CD3+CD28",]
    
    # separate data in 2 groups
    dta_CD3_CD28num <- as.data.frame(apply(dta_CD3_CD28[, 4:16], 2, as.numeric), na.rm = T)
    # replace NAs by imputation
    cl <- kmeans(Hmisc::impute(dta_CD3_CD28num), 2)
    dta_CD3_CD28_grp1 <- dta_CD3_CD28[which(cl$cluster==1),]
    dta_CD3_CD28_grp2 <- dta_CD3_CD28[which(cl$cluster==2),]
    
    # then use the right group 
    if (dim(dta_CD3_CD28_grp1)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp1
      ind_CD3_CD28 <- dta_stim$DonorId
    }
    
    else if (dim(dta_CD3_CD28_grp2)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp2
      ind_CD3_CD28 <- dta_stim$DonorId
    }
  
    # use the right indices for the Null
    diffMat<- dta_stim[,4:16]-dta_Null[dta_stim$DonorId,4:16]
    medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
    id <- medianVal > log(1.3)
    protList <- colnames(dta_stim[4:16][,id])

    curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
    curr_dta[,1:3] <- dta_stim[,1:3]
    n <- length(protList)+3
    curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
    curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
    dta_stimul <- curr_dta
    dta_stimul <- merge.data.frame(dta_stimul, df_counts, by.x = "DonorId", by.y = "SUBJID")

  }
  
  if (stimul ==  "Null") {
    dta_stimul <- dataProt[dataProt$StimulusName == "Null",]
    dta_stimul <- merge.data.frame(dta_stimul, df_counts, by.x = "DonorId", by.y = "SUBJID")
    protList <- colnames(dta_stimul[4:16])
  }
  
  
  # merge the dataframes
  
  if (stimul == "CD3+CD28"){
    DF <- DF[match(ind_CD3_CD28, DF$DonorId),]
    DF <- merge.data.frame(dta_stimul, df_data_allsel, by.x = "DonorId", by.y = "SUBJID")
  } else {
    DF <- merge.data.frame(dta_stimul, df_data_allsel, by.x = "DonorId", by.y = "SUBJID")
  }
  
  
  # make regressions
  
  matList <- list()
  matDATA <- list()
  matDATAPval <- list()
  p_val <- list()
  
  listFit <- list()
  effect_size_E_list <- list()
  effect_size_sd_low_list <- list()
  effect_size_sd_high_list <- list()
  listFitPval <- list()
  p_val_list <- list()

 # for (crit in colnames(df_data_allsel %>% dplyr::select (-c('SUBJID', 'AGE.V0',  'SEX')))){
crit="CMV.V1"  

  listFit <- list()
  effect_size_E_list <- list()
  effect_size_sd_low_list <- list()
  effect_size_sd_high_list <- list()
  listFitPval <- list()
  p_val_list <- list()
 
  #stimul = "Null"
  for (i in protList) { 
    print (i)
    
    listCrit <- list()
    effect_size_E <- list()
    effect_size_sd_low <- list()
    effect_size_sd_high <- list()
    listPval <- list()
    
    #for (var in c(colnames(df_counts %>% dplyr::select (-c('SUBJID', 'CD4negCD8neg_NKT_HLADRpos'))))){ # N_CD4negCD8neg_NKT_HLADRpos.panel3 has 817 missing data
    
      for (var in c(colnames(df_counts %>% dplyr::select (-'SUBJID')))){
        #length(DF$var[!(is.na(DF$var))]) > 333
      
      if (crit %in% col_names_cat) {
        
        DF2 <- na.omit(DF[,c(var, crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 with crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x * z + AGE.V0 + SEX + BatchId), 
                                                         list( x=crit, y = i, z=var))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        fitmA <- anova(fitm)
        
      
        # model 2 without crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ z + AGE.V0 + SEX + BatchId ),
                                                          list(z=var, y = i))))[2], data=DF2)
        fitmA2 <- anova(fitm2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[var] <- fit[2,'Pr(>Chi)']
        
        # recover p-val and ES
        
        listCrit[var] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                           .Names=levelsCrit)
        
        p_val[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                   .Names=levelsCrit)
        
        effect_size_sd_low[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        effect_size_sd_high[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
      }
      
      else if (crit %in% col_names_num) {
        
        DF2 <- na.omit(DF[,c(var, crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 with crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x * z + AGE.V0 + SEX + BatchId), 
                                                         list( x=crit, y = i, z=var))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        # model 2 without crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ z + AGE.V0 + SEX + BatchId),
                                                          list(z=var, y = i))))[2], data=DF2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[var] <- fit[2,'Pr(>Chi)']
        
        # recover p-val and ES
        
        listCrit[var] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                           .Names=levelsCrit)
        
        p_val[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                   .Names=levelsCrit)
        
        effect_size_sd_low[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        effect_size_sd_high[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
      }
      
      # add the no covar possibility at the begining
      var <- "ABSENT"
      
      if (crit %in% col_names_cat) {
        
        DF2 <- na.omit(DF[,c(crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 witjout crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x + AGE.V0 + SEX + BatchId), 
                                                         list( x=crit, y = i))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        fitmA <- anova(fitm)
        
        # model 2 with crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~  AGE.V0 + SEX + BatchId ),
                                                          list(z=var, y = i))))[2], data=DF2)
        fitmA2 <- anova(fitm2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[var] <- fit[2,'Pr(>Chi)']
        
        # recover p-val and ES
        listCrit[var] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                          .Names=levelsCrit)
        
        p_val[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                  .Names=levelsCrit)
        
        effect_size_sd_low[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        effect_size_sd_high[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
      }
      
      else if (crit %in% col_names_num) {
        
        DF2 <- na.omit(DF[,c(crit,i,'AGE.V0', 'SEX', 'BatchId')])
        
        # model 1 without crit
        fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ x + AGE.V0 + SEX + BatchId), 
                                                         list( x=crit, y = i))))[2], data=DF2)
        indCrit <- grep(crit,names(coef(fitm)))
        levelsCrit <- names(coef(fitm))[indCrit]
        
        
        # model 2 with crit
        fitm2 <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ AGE.V0 + SEX + BatchId),
                                                          list( y = i))))[2], data=DF2)
        
        fit <- anova(fitm, fitm2, test = 'Chisq')
        
        listPval[var] <- fit[2,'Pr(>Chi)']
       
        
        # recover p-val and ES
        listCrit[var] <- min(summary(fitm)$coefficients[grep(crit, rownames(summary(fitm)$coefficients)),'Pr(>|t|)'])
        
        effect_size_E[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Estimate'][indCrit],
                                          .Names=levelsCrit)
        
        p_val[[var]] <- structure(.Data=summary(fitm)$coefficients[,'Pr(>|t|)'][indCrit],
                                  .Names=levelsCrit)
      
        effect_size_sd_low[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,1], .Names=levelsCrit)
        effect_size_sd_high[[var]] <- structure(.Data=confint(fitm, parm=levelsCrit , level=0.95)[,2], .Names=levelsCrit)
        
        
      }
      
      
   # } # crit loop
    
    listFit[[i]] <- unlist(listCrit)
    
    listFitPval[[i]] <- unlist(listPval)
    
    effect_size_E_list[[i]] <- unlist(effect_size_E)
    effect_size_sd_low_list[[i]] <- unlist(effect_size_sd_low)
    effect_size_sd_high_list[[i]] <- unlist(effect_size_sd_high)
    p_val_list[[i]] <- unlist(p_val)
  }
  
  
  # recreate matrices
    
  mat_effect_size_E[[crit]] <- as.data.frame(effect_size_E_list)
  mat_effect_size_sd_low[[crit]] <- as.data.frame(effect_size_sd_low_list)
  mat_effect_size_sd_high[[crit]] <- as.data.frame(effect_size_sd_high_list)
  mat_p_val[[crit]] <- as.data.frame(p_val_list)
  
  # FDR for all
  
  matDATAPval <- as.data.frame(listFitPval)
  matDATAPvalFDR <-matrix(nrow=nrow(matDATAPval), ncol=ncol(matDATAPval), data=p.adjust(unlist(matDATAPval), method='BY'))
  colnames(matDATAPvalFDR) <- colnames(matDATAPval)
  rownames(matDATAPvalFDR) <- rownames(matDATAPval)
  
  melted_matDATA <- melt(as.matrix(matDATAPvalFDR))
  
  melted_matDATA$value <- -log10(melted_matDATA$value)
  melted_matDATA$stars <- cut(melted_matDATA$value, breaks=c(-Inf, 1.30103, 2, 3, Inf), label=c("", "*", "**", "***"))
  medianValue <- median(melted_matDATA$value, na.rm=T)
  
  melted_matDATA_ordered <- melted_matDATA[order(as.character(melted_matDATA$Var1)),]
  
   
  #  heatmap
  heatmapList[[crit]] <-  ggplot(melted_matDATA_ordered, aes(x=Var2, y=Var1, fill=value)) +
    geom_tile()+
    #scale_fill_gradient2(low="dark blue", mid="light blue", high="red", midpoint=medianValue) + #midpoint=-log10(0.05)
    scale_fill_gradient2(low="#471164FF", mid="#443A83", high="#AADC32FF", midpoint=medianValue) + #midpoint=-log10(0.05) # pas mal
    #scale_fill_gradient2(low="#471164FF", mid="#2C728E", high="#AADC32FF", midpoint=medianValue) + #midpoint=-log10(0.05)
    geom_text(aes(label=stars), color="black", size=3) +
    labs(y="76 cell subsets", x="", fill="-log10(adjPval)") +
    theme_bw() + theme(axis.text.x=element_text(angle = -90, hjust = 0))+
    theme(axis.text.x = element_text(size = 12)) +
    theme(axis.text.y = element_text(size = 8)) +
    scale_y_discrete(name="", limits = sort(levels(melted_matDATA_ordered$Var1), decreasing=T)) +
    ggtitle(paste0('Stimulus = ', stimul, ' crit= ', crit))
  
 
  ggsave(plot=marrangeGrob(grobs=heatmapList, nrow=1, ncol=1), filename = paste0(pathRes, '/Heatmap_CMVvsCells_', stimul, Sys.Date(), '.pdf'), width= 8.5, height=11)
  
   write.table(as.data.frame(melted_matDATA_ordered),file=paste0(pathRes,"/HeatmapsCMVvsCells_values_", stimul,"_", Sys.Date(),".txt"), quote=F, row.names = F, col.names = T, sep="\t")
  
  }

  
# save session info and environment
#packagesVersions <- sessionInfo()
#save.image(file=paste0('./CMVVsCells_', Sys.Date(), '.RData'))
````

  
  