---
title: "Milieu Intérieur Project: Cytokine Data Analysis"
date: "2023-06-10"
author: "Violaine Saint-André"

## License
#  Milieu Intérieur Project: Cytokine Data Analysis
#     Copyright (C) 2023  Violaine Saint-André
#     contact: violaine.saint-andre@pasteur.fr
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
---

## Load libraries
```{r, results="hide"}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(FactoMineR) 
library(factoextra)

pathRes <- "./RESULTS"

```


## Import proteomic matrix

```{r, results="hide"}
df.data <- read.table(file="./TableS1.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE)

# remove the donors that have been reprocessed
  # adding 302 as it is missing values for LPS 
  # removed 883 who removed consent for everything
df.data.v1 <- df.data %>% 
  filter(!(DonorId %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701, 302, 883))) 

dta <- df.data.v1[,c(1,2:ncol(df.data.v1))]

#Log transformation
dta.log <- dta
dta.log[,4:ncol(dta)] <- log(dta[,4:ncol(dta)])
dataProt <- dta.log

head(dataProt)

```

## Import covariates
```{r, results="hide"}

# on all selected variables
df_data_all <- read.table(file="./TableS2.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE) 
colnames(df_data_all)

#df_data_all <- df_data_all %>% dplyr::select(-c("AGE.V0","AGE","SEX", "BATCHID"))

# define categorical and numerical variables
col_names_cat <- list()
col_names_num <- list()

#df_datavar <- read.table(file = "./Variable_trans_mod.csv",
#                           sep = ";",
#                           dec = ",",
#                           header = TRUE,
#                           fill = TRUE,
#                           stringsAsFactors = FALSE)
#df_datavarShort <- df_datavar[,c("VARIABLE","VAR.DESC", "VAR.VAL","Value", "CATEGORY")]

#df_datavarShort <- df_datavarShort[df_datavarShort$VARIABLE %in% names(df_data_all),]
#dim(df_datavarShort) 
#write.table(as.data.frame(df_datavarShort),paste("./df_datavarShort.txt"),  quote=F, row.names = F, sep="\t")

df_datavar <- read.table(file = "./df_datavarShort.txt",
                           sep = "\t",
                           dec = ",",
                           header = TRUE,
                           fill = TRUE,
                           stringsAsFactors = FALSE)

df_datavar_cat <- df_datavar %>% filter(CATEGORY %in% c("cat"))
df_datavar_num <- df_datavar %>% filter(CATEGORY %in% c("num"))
df_datavar_all <- df_datavar %>% filter(CATEGORY %in% c("cat", "num", "likert"))
  
curr_col_names_cat <- intersect(df_datavar_cat$VARIABLE, names(df_data_all))
curr_col_names_num <- intersect(df_datavar_num$VARIABLE, names(df_data_all))
curr_col_names_all <- intersect(df_datavar_all$VARIABLE, names(df_data_all))

# transform numerical data into numeric  
df_data_all[,curr_col_names_num] <- apply(df_data_all[,curr_col_names_num, drop=F],2, function(x) as.numeric(gsub(",", ".", as.character(x))))
df_data_all[,curr_col_names_cat] <- apply(df_data_all[,curr_col_names_cat, drop=F],2, function(x) as.character(x))
  
col_names_cat <-c(col_names_cat, curr_col_names_cat)
col_names_num <-c(col_names_num, curr_col_names_num)


# > colnames(df_data_all)
#   [1] "SUBJID"         "SEASON"         "CHEVEUX"        "CORREC"         "CORRECP"        "LOG"           
#   [7] "PHYSL"          "PHYSP.T1"       "VILLENPOP20"    "VILLESPOP20"    "VIT"            "VIT.COUPLE"    
#  [13] "VIT.ENFANTS"    "YEUX.T1"        "NVILLES"        "PHYSDUR.T1"     "PHYSJ"          "PHYST.T1"      
#  [19] "VILLENPOP"      "VILLESPOP"      "BRUIT"          "CSP"            "EMPLOIP"        "EMPLOIS"       
#  [25] "INACT"          "NIVETUD"        "POUSS"          "PTOX"           "REVENUS"        "TRAVJ"         
#  [31] "TRAVT"          "AMIDI"          "DEJ"            "DINER"          "GRIGN"          "MATIN"         
#  [37] "NCOLL"          "PDEJ"           "PRODALL1"       "PRODALL2"       "PRODALL3"       "PRODALL4"      
#  [43] "REPASH"         "SEL"            "SOIREE"         "ALCF"           "BIERE"          "CUISIN"        
#  [49] "DESS"           "DIFFATM"        "FASTF"          "FCRUS"          "FCUITS"         "FECUL"         
#  [55] "FRITS"          "FROM"           "PLATC"          "RESTAU"         "VIANDE"         "VIENN"         
#  [61] "VIN"            "VITA"           "VORALE"         "PSEXP"          "TABAC.T1"       "NBYLPSEXP"     
#  [67] "NBYLTABAC"      "NBYPSEXP"       "NBYTABAC"       "TOTNROFCIGS"    "DORDIF"         "DORLUM"        
#  [73] "HASCHICH"       "STRESS"         "CONCEN"         "DIFF"           "DORH.T1"        "FATI"          
#  [79] "MBLESS"         "PLAIS"          "TRIS"           "ACCOUCH"        "ALIM"           "VOIE"          
#  [85] "ACCOUNB"        "ALIMDUR"        "NAISSP"         "NAISST"         "TONSILLECTOMY"  "APPENDICECTOMY"
#  [91] "OTHER"          "MEASLES"        "HEPATITISB"     "FLU"            "MEASLESMH"      "RUBELLAMH"     
#  [97] "CHICKENPOXMH"   "MUMPSMH"        "OTHERMH"        "SURGICAL.INT"   "MUMPS"          "RUBELLA"       
# [103] "CMSEQ"          "CMSTDT"         "ABDOCM.V0"      "BMI.V0"         "DIABP1.V0"      "DIABP2.V0"     
# [109] "FC.V0"          "HEIGHT.V0"      "SYSBP1.V0"      "TEMP.V0"        "WEIGHT.V0"      "ALLER"         
# [115] "ATTAQUE"        "CAUTRE"         "CCOLON"         "CSEIN"          "DIABETE"        "HYPERT"        
# [121] "INFARC"         "CMV.V1"         "EBV.EA.V1"      "EBV.EBNA.V1"    "HBS.V1"         "HP.V1"         
# [127] "HSV1.V1"        "HSV2.V1"        "ORE.V1"         "ROUG.V1"        "TXP.V1"         "VZV.V1"        
# [133] "HP.V1.QT"                                             


```

# Run regressions
```{r, results="hide"}
# prepare the lists

mat_residus <- list()
mat_res <- list()
df.dataProtList <- list()


# loop on all stimulations 
  
for (stimul in c("SEB", "E.coli",  "CD3+CD28", "LPS", "BCG")){  #"BCG", "C.albicans",, "PolyIC", "Null","Influenza","IL1b", 'IFNg',"TNFa"
  
#stimul <- "LPS"

  print(paste0('stimul=',stimul))
  diffMat <- matrix(stimul, nrow = 998, ncol = 12)
  
  # to work on expressed prot only
  dta_Null <- dataProt[dataProt$StimulusName == "Null",]
  dta_stim <- dataProt[dataProt$StimulusName == stimul,]
  diffMat<- dta_stim[,4:16]-dta_Null[,4:16]
  
  medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
  id <- medianVal > log(1.3)
  protList <- colnames(dta_stim[4:16][,id])  
  
  curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
  curr_dta[,1:3] <- dta_stim[,1:3]
  n <- length(protList)+3
  curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
  curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
  dta_stimul <- curr_dta
  
  
    # exceptions
  
  if (stimul == "TNFa") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "TNFa")] 
    protList <- setdiff(protList, "TNFa")
  }
  
  if (stimul == "IL1b") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "IL1b")] 
    protList <- setdiff(protList, "IL1b")
  }
  
  if (stimul == "IFNg") {
    dta_stimul <- dta_stimul[, setdiff(colnames(dta_stimul), "FNg")] 
    protList <- setdiff(protList, "IFNg")
 }
                      
                    
   if (stimul ==  "CD3+CD28") {
    dta_CD3_CD28 <- dataProt[dataProt$StimulusName == "CD3+CD28",]
    
    # separate data in 2 groups
    dta_CD3_CD28num <- as.data.frame(apply(dta_CD3_CD28[, 4:16], 2, as.numeric), na.rm = T)
    # replace NAs by imputation
    cl <- kmeans(Hmisc::impute(dta_CD3_CD28num), 2)
    dta_CD3_CD28_grp1 <- dta_CD3_CD28[which(cl$cluster==1),]
    dta_CD3_CD28_grp2 <- dta_CD3_CD28[which(cl$cluster==2),]
    
    # then use the right group 
    if (dim(dta_CD3_CD28_grp1)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp1
      ind_CD3_CD28 <- dta_stim$DonorId
    }
    
    else if (dim(dta_CD3_CD28_grp2)[1] ==705){
      dta_stim <- dta_CD3_CD28_grp2
      ind_CD3_CD28 <- dta_stim$DonorId
    }
  
    # use the right indices for the Null
    diffMat<- dta_stim[,4:16]-dta_Null[dta_stim$DonorId,4:16]
    medianVal <- apply(diffMat[,],2, function(x) abs(median(x,na.rm=T)))
    id <- medianVal > log(1.3)
    protList <- colnames(dta_stim[4:16][,id])

    curr_dta <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(dta_stim)))
    curr_dta[,1:3] <- dta_stim[,1:3]
    n <- length(protList)+3
    curr_dta[,4:n] <- dta_stim[, c(colnames(dta_stim) %in% protList)]
    curr_dta <- curr_dta[rowSums(is.na(curr_dta)) == 0,]
    dta_stimul <- curr_dta

  }
  
  if (stimul ==  "Null") {
    dta_stimul <- dataProt[dataProt$StimulusName == "Null",]
    protList <- colnames(dta_stimul[4:16])
  }
  
  
  # merge the dataframes
  
  if (stimul == "CD3+CD28"){
    DF <- DF[match(ind_CD3_CD28, DF$DonorId),]
    DF <- merge.data.frame(dta_stimul, df_data_all, by.x = "DonorId", by.y = "SUBJID")
  } else {
    DF <- merge.data.frame(dta_stimul, df_data_all, by.x = "DonorId", by.y = "SUBJID")
  }
  
  # make regressions
  
  
  mat_residus <- list()
  residusUnlist <- list()
  residus <- list()
 
  for (i in protList) { 
    print (i)

    DFshort <- na.omit(DF[,c(i,'AGE.V0', 'SEX', 'BatchId')])
    rownames(DFshort) = DF$DonorId
       
         fitm <- lm(gsub('\\"',"",as.character(substitute(expression(y ~ AGE.V0 + SEX + BatchId), 
                                                        list( y = i))))[2], data=DFshort)
         residus[[i]] <- residuals(fitm)
    }
  residusUnlist <- unlist(residus)
  mat_residus <- as.data.frame(residusUnlist)
  rownames <- row.names(mat_residus)
  res <- strsplit(rownames, ".", fixed = TRUE)
  inter <- do.call(rbind, res)
  mat_res$DonorId <- inter[ ,2]
  mat_res$Cytokine <- inter[ ,1]
  mat_res$Residus <-  mat_residus$residusUnlist
  matPlot <- as.data.frame(mat_res)
  
  df_data_allselNA <- df_data_all
df.dataProt <- merge(matPlot, df_data_allselNA, by.x='DonorId', by.y='SUBJID')

df.dataProt$SMOKING[df.dataProt$TABAC.T1=="2"]<- "Active Smoker"
df.dataProt$SMOKING[df.dataProt$TABAC.T1=="1"]<- "Past Smoker"
df.dataProt$SMOKING[df.dataProt$TABAC.T1=="0"]<- "Never"


df.dataProtList[[stimul]] <- df.dataProt
df.dataProtList[[stimul]]$StimulusName <- stimul
}

```

###rearrange variables
```{r, results="hide"}

df_data_allselNA <- df_data_all
df_data_allselNA$TOTNROFCIGS[df_data_allselNA$TOTNROFCIGS==0] <- NA
df_data_allselNA$NBYLTABAC[df_data_allselNA$NBYLTABAC==0]<- NA
df_data_allselNA$NBYTABAC[df_data_allselNA$NBYTABAC==0]<- NA
df_data_allselNA$TABAC.T1[df_data_allselNA$TABAC.T1==0]<- NA
df.dataProt <- merge(matPlot, df_data_allselNA, by.x='DonorId', by.y='SUBJID')

df.dataProt$SMOKING[df.dataProt$TABAC.T1=="2"]<- "Active Smoker"
df.dataProt$SMOKING[df.dataProt$TABAC.T1=="1"]<- "Past Smoker"
df.dataProt$SMOKING[df.dataProt$TABAC.T1=="0"]<- NA

# Create plot by stim
  curr.colour <- 'SMOKING'
  
    p <- ggplot(data=df.dataProt  %>% filter(SMOKING %in% c("Active Smoker", "Past Smoker")), # ajouté le dernier filtre pour cette version
                aes_string(x='NBYTABAC' , y="Residus", colour=curr.colour)) + 
      geom_point(size=1) +
      geom_smooth(method=lm, se = TRUE) +
      theme_bw() + 
      facet_wrap(~Cytokine, scale="free", ncol=5) +
      theme(strip.background =element_rect(fill="white"), strip.text = element_text(size = 15))+
      scale_color_manual(values=c("#F8766D", "#6E9CF8"))

    # save as PDF
    ggsave(plot=p, 
           filename = paste0(pathRes,'NBYTABAC_ResidusAgeSexBatchId',
            stimul,'_colouredBy-all_col_',curr.colour,'-', Sys.Date(), '.pdf'), width = 12, height=14)

   ##save session info and environment
#packagesVersions <- sessionInfo()

#save.image(file=paste0('/Users/saint-andre/Documents/MI/Environments/Residuals_', Sys.Date(), '.RData'))
```

###create boxplots
```{r, results="hide"}
# rename TABAC.T1 levels 1, 2, 3
library('ggsignif')

df.dataProtbind <- rbind(df.dataProtList$E.coli,df.dataProtList$SEB, df.dataProtList$`CD3+CD28`, df.dataProtList$LPS, df.dataProtList$BCG)

# genererate Stimulus-centered view for each prot for each crit

crit='TABAC.T1'  

   protein="CXCL5" 
    p_coli_lps <- ggplot(data=df.dataProtbind %>% filter(Cytokine==protein) %>% filter(StimulusName %in% c("E.coli", "LPS")), 
                aes_string(x=crit, y='Residus')) + #, colour=crit
                geom_boxplot(outlier.shape=NA) +
                geom_jitter(alpha = 0.1) +
                theme_classic()+
                facet_wrap(~StimulusName, ncol=3, scale="free") +
                geom_signif( comparisons = list(c("0", "1"), c("1", "2"), c("0","2")), test = "wilcox.test", map_signif_level=TRUE) +
                ylim(-2.5,3)+ # for res CXCL5
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
                scale_fill_viridis_d() +
                ggtitle(paste0('Crit = ', crit, ' Prot = ', protein))
    
    # save as PDF
    ggsave(plot=p_coli_lps, filename = paste0(pathRes,'/plotResiduals_', protein,'_',crit,'_coli_lps_', Sys.Date(), '.pdf'), width = 7, height=7)
                
     protein="IL2" 
    p_seb_cd3cd28 <- ggplot(data=df.dataProtbind %>% filter(Cytokine==protein) %>% filter(StimulusName %in% c("SEB", "CD3+CD28")), 
                aes_string(x=crit, y='Residus')) + #, colour=crit
                geom_boxplot(outlier.shape=NA) +
                geom_jitter(alpha = 0.1) +
                theme_classic()+
                facet_wrap(~StimulusName, ncol=3, scale="free") +
                geom_signif( comparisons = list(c("0", "1"), c("1", "2"), c("0","2")), test = "wilcox.test", map_signif_level=TRUE) +
                ylim(-2.5,3)+ # for res IL2
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
                scale_fill_viridis_d() +
                ggtitle(paste0('Crit = ', crit, ' Prot = ', protein))
    
    ggsave(plot=p_seb_cd3cd28, filename = paste0(pathRes,'/plotResiduals_', protein,'_',crit, '_seb_cd3cd28_', Sys.Date(), '.pdf'), width = 7, height=7)

``` 
