---
title: "Milieu Intérieur Project: Cytokine Data Analysis"
date: "2023-06-10"
author: "Violaine Saint-André"

## License
#  Milieu Intérieur Project: Cytokine Data Analysis
#     Copyright (C) 2023  Violaine Saint-André
#     contact: violaine.saint-andre@pasteur.fr
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
##
---

## Load libraries
```{r, results="hide"}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(FactoMineR) 
library(factoextra)

pathRes <- "./RESULTS"

```


## Import proteomic matrix

```{r, results="hide"}
df.data <- read.table(file="./TableS1.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE)

# remove the donors that have been reprocessed
  # adding 302 as it is missing values for LPS 
  # removed 883 who removed consent for everything
df.data.v1 <- df.data %>% 
  filter(!(DonorId %in% c(96, 104,	122,	167,	178,	219,	268,	279,	303,	308,	534,	701, 302, 883))) 

dta <- df.data.v1[,c(1,2:ncol(df.data.v1))]

#Log transformation
dta.log <- dta
dta.log[,4:ncol(dta)] <- log(dta[,4:ncol(dta)])
dataProt <- dta.log

head(dataProt)

```

## Import covariates
```{r, results="hide"}
# on all selected variables
df_data_all <- read.table(file="./TableS2.txt", header=TRUE, sep='\t', stringsAsFactors = FALSE) 
colnames(df_data_all)

df_data_all <- df_data_all %>% dplyr::select(-c("AGE","BATCHID"))

length(df_data_all) 

# set categorical and numerical variables
col_names_cat <- list()
col_names_num <- list()

df_datavar <- read.table(file = "./df_datavarShort.txt",
                         sep = "\t",
                         dec = ",",
                         header = TRUE,
                         fill = TRUE,
                         stringsAsFactors = FALSE)

df_datavar_cat <- df_datavar %>% filter(CATEGORY %in% c("cat"))
df_datavar_num <- df_datavar %>% filter(CATEGORY %in% c("num"))
df_datavar_all <- df_datavar %>% filter(CATEGORY %in% c("cat", "num", "likert"))

curr_col_names_cat <- intersect(df_datavar_cat$VARIABLE, names(df_data_all))
curr_col_names_num <- intersect(df_datavar_num$VARIABLE, names(df_data_all))
curr_col_names_all <- intersect(df_datavar_all$VARIABLE, names(df_data_all))

# put all covars as numeric for the PCA
df_data_all[,curr_col_names_num] <- apply(df_data_all[,curr_col_names_num, drop=F],2, function(x) as.numeric(gsub(",", ".", as.character(x))))

# Add age_cat variable
df_data_all[,"Age"] <- cut(df_data_all[,"AGE.V0"], breaks= c(20,30,40,50,60,70), labels = c("1","2","3", "4", "5"))
df_data_all[,"Age"] <- apply(df_data_all[,"Age", drop=F],2, function(x) as.numeric(as.character(x)))


# merge with the prot matrix
ri.df.v1log <- merge.data.frame(dataProt,df_data_all, by.x = "DonorId", by.y = "SUBJID")

```

## Create PCAs
```{r, results="hide", warning=FALSE}

respca <- FactoMineR::PCA(X = ri.df.v1log, 
                         scale.unit = TRUE,  #if TRUE, the data are scaled to unit variance before the analysis. 
                         graph = F, #if TRUE, the graphs are displayed.
                         ncp = 13, #number of PCs to keep.
                         quali.sup = c(1:3, 17:149)) #indexes of the annotation columns,
                                          

habillage <- 'StimulusName'

pcaPlot <- fviz_pca_biplot(respca, 
                axes = c(1,2), ## axes to be plotted
                habillage = habillage, ## how to color the points
                select.var = list(cos2 = 0.02), ## threshold to be applied to select variables based on their contributions
                invisible = c("quali"), 
                label="var",
                #select.var = list(cos2 = 0.8),
                pointsize = 2,
                labelsize = 4) ## to not superimpose "centroid" points by group

# change color of PCA according to stimulation types
  pcaPlot <- pcaPlot + 
    scale_color_manual(values=c( "SEB"="firebrick1",
                               "CD3+CD28"="firebrick4", 
                               "E.coli"="steelblue", 
                               "LPS"="royalblue2",
                               "C.albicans"="royalblue4", 
                               "BCG"= "cyan4", 
                               "PolyIC"= "springgreen3", 
                               "Influenza"= "springgreen4", 
                               "IFNg"="grey80", 
                               "TNFa"="grey40",
                               "IL1b"="grey20", 
                               "Null"= "black" )
                     ) +
      theme_minimal()

pcaPlot

ggsave(plot=pcaPlot, filename = paste0(pathRes,'/pcaPlots_log_', habillage, '_', Sys.Date(), '.pdf'), width = 8, height=8)
```

## Plot PCAs by stimultions
```{r, results="hide", warning=FALSE}

# color by age, and sex, smoking, season and batchID  

  colnames(ri.df.v1log) <- gsub( "TABAC.T1","Smoking", colnames(ri.df.v1log))
  colnames(ri.df.v1log) <- gsub( "SEX","Sex", colnames(ri.df.v1log))
  colnames(ri.df.v1log) <- gsub( "SEASON","Season", colnames(ri.df.v1log))
  


for (hab in c("Age", "Sex", "Smoking", "BatchId", "Season")){ 
  
  pcaPlotsEach <- list()

 for (curr.stimulation in c("Null", "BCG",  "C.albicans", "IL1b", "SEB", "E.coli", "Influenza", 'IFNg', "CD3+CD28",   "LPS",   "PolyIC", "TNFa" )){ 
    
    subset <- ri.df.v1log %>% filter(StimulusName %in% curr.stimulation) 
    
    respca <- FactoMineR::PCA(X = subset, 
                           # scaled to unit variance before the analysis. 
                           scale.unit = TRUE,  
                           graph = F, 
                           # number of PCs to keep.
                           ncp = 13, 
                           # indexes of the annotation columns
                           quali.sup = c(1:3, 17:150))  
  
  # Superimpose sample projections and variable contributions on a biplot.
    pcaPlotsEach[[curr.stimulation]] <- fviz_pca_ind(respca, 
                                                      # axes to be plotted
                                                      axes = c(1,2), 
                                                      habillage=hab,
                                                      # to remove the names of individuals
                                                      label ="var", 
                                                      invisible = c("quali"), 
                                                      title=paste0(curr.stimulation),
                                                      arrowsize = 0.5,
                                                      pointsize = 0.5,
                                                      # to not superimpose 
                                                      labelsize = 2) 
  
  }

ggsave(plot=marrangeGrob(grobs=pcaPlotsEach, nrow=1, ncol=1), 
       filename = paste0(pathRes,'/pcaPlots_byStim_', hab, '_', Sys.Date(), '.pdf'),
       width = 5, height=5
       )


      pdf(paste0(pathRes, '/PCAPlots_',hab, '_',  Sys.Date(), '.pdf'))
     plot2 <- plot_grid(pcaPlotsEach$Null,pcaPlotsEach$SEB, pcaPlotsEach$`CD3+CD28`, pcaPlotsEach$BCG, pcaPlotsEach$E.coli, pcaPlotsEach$LPS, pcaPlotsEach$C.albicans, pcaPlotsEach$Influenza, pcaPlotsEach$PolyIC, pcaPlotsEach$IL1b, pcaPlotsEach$IFNg, pcaPlotsEach$TNFa,
                                    nrow = 4, ncol = 3,  
                       align = "vh", 
                       axis = "lb", width = 8.5, height= 11)
     print(plot2) 
     dev.off()
     

}
```


